In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder=OrdinalEncoder(categories=[['female','male']])
dataset[['sex']]=ordinal_encoder.fit_transform(dataset[['sex']])

In [5]:
dataset[['sex']]=dataset[['sex']].astype(int)

In [6]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder=OrdinalEncoder(categories=[['yes','no']])
dataset[['smoker']]=ordinal_encoder.fit_transform(dataset[['smoker']])

In [7]:
dataset[['smoker']]=dataset[['smoker']].astype(int)

In [8]:
dataset.head()

   age  sex     bmi  children  smoker      charges
0   19    0  27.900         0       0  16884.92400
1   18    1  33.770         1       1   1725.55230
2   28    1  33.000         3       1   4449.46200
3   33    1  22.705         0       1  21984.47061
4   32    1  28.880         0       1   3866.85520

In [9]:
independent=dataset[['age', 'sex', 'bmi', 'children', 'smoker']]

In [10]:
dependent=dataset[['charges']]

In [38]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid={'criterion':['poisson','squared_error','friedman_mse','absolute_error'],
            'max_features':['sqrt','log2'],
            'splitter':['best','random']}

grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['poisson', 'squared_error',
                                       'friedman_mse', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [12]:
print(grid.best_params_)

{'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}

In [13]:
result=grid.cv_results_

In [14]:
table=pd.DataFrame.from_dict(result)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010647,0.002339,0.004531,0.000620,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.711992,0.570316,0.570457,0.744518,0.713224,0.662102,0.075787,9
1,0.007437,0.000788,0.003708,0.000859,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.759005,0.628727,0.691208,0.707145,0.614289,0.680075,0.053012,2
2,0.007849,0.000607,0.003243,0.000484,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.772885,0.627894,0.436467,0.623589,0.714832,0.635133,0.114001,15
3,0.005856,0.000429,0.003822,0.000550,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.658247,0.617600,0.677449,0.699859,0.618073,0.654246,0.032516,10
4,0.007385,0.000751,0.003391,0.000507,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.669722,0.587637,0.630925,0.722033,0.729917,0.668047,0.054017,8
5,0.007489,0.001083,0.003866,0.000600,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.734362,0.413755,0.730478,0.695556,0.664682,0.647767,0.119726,11
6,0.008052,0.001683,0.004611,0.002216,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.672411,0.621177,0.683013,0.736124,0.675288,0.677603,0.036525,5
7,0.006102,0.000479,0.004119,0.001030,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.691923,0.515867,0.704603,0.699830,0.577552,0.637955,0.077119,14
8,0.007740,0.002991,0.004624,0.001717,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.684315,0.670273,0.682556,0.729912,0.792436,0.711898,0.045090,1
9,0.006250,0.002726,0.003898,0.000198,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.682791,0.565957,0.771320,0.682986,0.685544,0.677720,0.065371,4
10,0.006851,0.001315,0.004005,0.000631,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.724024,0.596282,0.732097,0.591619,0.747521,0.678308,0.069306,3
11,0.005738,0.000620,0.003710,0.000407,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.687924,0.630802,0.724225,0.703478,0.595859,0.668458,0.047757,7
12,0.021564,0.001547,0.002809,0.000222,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.558362,0.575316,0.735746,0.660163,0.631572,0.632232,0.063548,16
13,0.016415,0.001728,0.002607,0.000493,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.603553,0.597723,0.719524,0.718751,0.734705,0.674851,0.060889,6
14,0.020194,0.002092,0.003184,0.000481,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.647220,0.503718,0.683592,0.697300,0.679197,0.642205,0.071163,13
15,0.012841,0.000998,0.003013,0.000704,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.673753,0.576030,0.665792,0.669759,0.627986,0.642664,0.037124,12

In [16]:
age=float(input("Age:"))
bmi=float(input("Bmi:"))
children=float(input("Children:"))
sex=float(input("sex male 0 or 1"))
smoker=float(input("yes 0 or 1"))

Age: 4
Bmi: 56
Children: 5
sex male 0 or 1 5
yes 0 or 1 3

In [17]:
pred=grid.predict([[age,bmi,children,sex,smoker]])
print("Future Pediction={}".format(pred))

Future Pediction=[11884.04858]

C:\Users\91636\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(